[[libass]]
arch = "aarch64"
git-tree-sha1 = "a3e73ecf5d803bb3792a23f0382a2b5573383647"
os = "macos"

    [[libass.download]]
    sha256 = "05508d65e4e0327e2174bf223ff306e13b5dfcd181304396a35ead6d96c6006a"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.aarch64-apple-darwin.tar.gz"
[[libass]]
arch = "aarch64"
git-tree-sha1 = "7921bf88954f26dc2e67265f5792accf6c60b704"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "b3a8535b9ec8aa50ae26b7ed5a094275a2b1f59d45aa81a092a38f4e44534760"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.aarch64-linux-gnu.tar.gz"
[[libass]]
arch = "aarch64"
git-tree-sha1 = "b04bf1cfb61812d0cd8e6e21ff805a49f2cb804f"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "027ec7eb431eda2cca1ee13e0370e1e5bd8f8c4121b136bd274c1fc36c249012"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.aarch64-linux-musl.tar.gz"
[[libass]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e4c16b3ff48f6eb183bed62a98dfce9256106752"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "2689dbbd4483be4a9edd86c5aa3568d4d8fc3f5beffc09b8477db2bea236e391"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.armv7l-linux-gnueabihf.tar.gz"
[[libass]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f8e5e14c234f17b2e254714c7f76fe25bac848a"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "aa62551da4228260be86f809252723c3068a1f23fccb1fbb86271d30337a9cc2"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.armv7l-linux-musleabihf.tar.gz"
[[libass]]
arch = "i686"
git-tree-sha1 = "3e90d47c5144bc426e80a17c4f9a2d49f3c85053"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "e90cf013ad8f1cfecc6bd9a922e93f75f6595c1665f57ea967c5a5d62805c957"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.i686-linux-gnu.tar.gz"
[[libass]]
arch = "i686"
git-tree-sha1 = "fc88f3910e6d4daf1e12e64dd03105aa9a69f972"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "be7889b8efc0cbc37fa35e93fa1f9af281c7218d724aa961df82d95e2ddb0947"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.i686-linux-musl.tar.gz"
[[libass]]
arch = "i686"
git-tree-sha1 = "6f884933fa6d451d4c8aafb71f03c3d85e927cae"
os = "windows"

    [[libass.download]]
    sha256 = "9f2730a693028638d17402a788fa91124e10870ea6eec543086195897c00280a"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.i686-w64-mingw32.tar.gz"
[[libass]]
arch = "powerpc64le"
git-tree-sha1 = "c01cb521d0822fceb9e8be868f80c01d9017297f"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "27dec70c623f2819c28a0b9fae8c6f7ddcdcce21fd3bc0fd9bd3efe33374fae5"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.powerpc64le-linux-gnu.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "096f050117a5d911291a7a3d322547214e4ba8d4"
os = "macos"

    [[libass.download]]
    sha256 = "cfd68b0afcb431972f0347ea5c8459bab130cb476037b1564f029d41f80e0c38"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.x86_64-apple-darwin.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "bd1f25e7053ebc00ee7d82f3c5ec4cf1e9a51e17"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "958a0508944e9a438164e022178f91d2d3a3a4050589636033d50b9425c0c1a6"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.x86_64-linux-gnu.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "f944fb1e4f68f3fe702d41be03d7d80def4cc5f8"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "c11c8e2f033b1602ddd75208db992e94d8cddcb7c30caa77530dd9f32ce5751e"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.x86_64-linux-musl.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "5cfe3d269fd08fecc04d2f6175a0200d7e016d4e"
os = "freebsd"

    [[libass.download]]
    sha256 = "9277ea897661d5983b980898a81b13c2649f5cd7f92974c9401f38709c6572bd"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.x86_64-unknown-freebsd.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "ba086fd5c33e4739579fd912fe0be3c73684998a"
os = "windows"

    [[libass.download]]
    sha256 = "2959ac66554322d8dc078c08268608830c866e6ea23c178aa1c501a5765aa7cc"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.2+0/libass.v0.15.2.x86_64-w64-mingw32.tar.gz"
